version: '3.1'

services:
    database:
        image: 'postgres:16.1'
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: 'pruebaconcepto'
            POSTGRES_PASSWORD: 'pruebaconcepto'