/*
 * SCRIPT DE INICIALIZACIÓN DE LA BASE DE DATOS
 */

-- CLIENTES
CREATE TABLE PCO_CLIENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(1024),
    PHONE VARCHAR(12),
    CREATED_DATE TIMESTAMP NOT NULL
);

CREATE SEQUENCE PCO_CLIENT_SEQ START 1;

-- HOTELES
CREATE TABLE PCO_HOTEL (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(1024),
    CREATED_DATE TIMESTAMP NOT NULL
);

CREATE SEQUENCE PCO_HOTEL_SEQ START 1;

-- RESERVAS
CREATE TABLE PCO_HOTELBOOKING (
    ID INT PRIMARY KEY,
    ID_HOTEL INT NOT NULL,
    ID_CLIENT INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(1024),
    CREATED_DATE TIMESTAMP NOT null,
    CONSTRAINT FK_HOTELBOOKIN_HOTEL FOREIGN KEY(ID_HOTEL) REFERENCES PCO_HOTEL(ID),
    CONSTRAINT FK_HOTELBOOKING_CLIENT FOREIGN KEY(ID_CLIENT) REFERENCES PCO_CLIENT(ID)
);

CREATE SEQUENCE PCO_HOTELBOOKING_SEQ START 1;
